discode/src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MessageRepository")
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="boolean")
     */
    private $epingler;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $room;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="messages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;


    public function __construct()
    {
        $this->room = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getEpingler(): ?bool
    {
        return $this->epingler;
    }

    public function setEpingler(bool $epingler): self
    {
        $this->epingler = $epingler;

        return $this;
    }

    public function getRoomId(): ?Room
    {
        return $this->room;
    }

    public function setRoomId(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
    public function __toString()
    {
        return 'message : '.$this->getDateCreation()->format('d/m/YY');
    }

}

discode/src/Entity/Room.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RoomRepository")
 */
class Room
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups("public")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("public")
     */
    private $nom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Message", mappedBy="room", orphanRemoval=true)
     */
    private $messages;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="rooms")
     */
    private $users;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->users = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setRoomId($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getRoomId() === $this) {
                $message->setRoomId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addRoom($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeRoom($this);
        }

        return $this;
    }

    public function __toString()
    {
        return 'room : '.$this->getNom();
    }

}

discode/src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Room;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RoomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('users')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
        ]);
    }
}

discode/src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Entity\Room;
use App\Form\RoomType;
use App\Repository\MessageRepository;
use App\Repository\RoomRepository;
use App\Repository\UserRepository;
use App\Service\MercureCookieGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mercure\PublisherInterface;
use Symfony\Component\Mercure\Update;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @Route("/room")
 */
class RoomController extends AbstractController
{
    /**
     * @Route("/", name="room_index", methods={"GET"})
     */
    public function index(RoomRepository $roomRepository): Response
    {
        return $this->render('room/index.html.twig', [
            'rooms' => $roomRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="room_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $room = new Room();
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($room);
            $entityManager->flush();

            return $this->redirectToRoute('room_index');
        }

        return $this->render('room/new.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_show", methods={"GET"})
     */
    public function show(Room $room, MercureCookieGenerator $cookieGenerator, MessageRepository $messageRepository): Response
    {
        if($this->getUser() == null){
            return $this->redirectToRoute('app_login');
        }else{
            $messages = $messageRepository->findBy(
                array('room' => $room->getId()),
                array('id' => 'DESC'),
                20
            );
            $response = $this->render('room/show.html.twig', [
                'room' => $room,
                'messages' => $messages
            ]);
            $response->headers->set('set-cookie', $cookieGenerator->generate($room));
            return $response;
        }
    }

    /**
     * @Route("/send/{room}", name="send", methods={"POST"})
     */
    public function send(MessageBusInterface  $bus, $room, SerializerInterface $serializer, RoomRepository $roomRepository, UserRepository $userRepository)
    {
        $target = [];
        $jsonEncode = array(
            'room'=> $room,
            'message' => $_POST['sendMessage'],
            'user' =>  $this->getUser()->getUsername()
        );
        $userLogged = $this->getUser();
        $criteria = array();
        $orderBy = array();
        $message = new Message();
        $message->setDateCreation(new \DateTime())
            ->setMessage($_POST['sendMessage'])
            ->setEpingler(false)
            ->setRoomId($roomRepository->find($room))
            ->setUser($userLogged);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($message);
        $entityManager->flush();
        $update = new Update(
            "http://127.0.0.1:8000/room/".$room,
            $serializer->serialize($jsonEncode, 'json'),
            $target
        );
        $bus->dispatch($update);
        return $this->redirectToRoute('room_show', array('id'=> $room));
    }
    /**
     * @Route("/{id}/edit", name="room_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Room $room): Response
    {
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('room_index');
        }

        return $this->render('room/edit.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="room_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Room $room): Response
    {
        if ($this->isCsrfTokenValid('delete'.$room->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($room);
            $entityManager->flush();
        }

        return $this->redirectToRoute('room_index');
    }
}

discode/templates/room/_delete_form.html.twig
<form method="post" action="{{ path('room_delete', {'id': room.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ room.id) }}">
    <button class="btn">Delete</button>
</form>

discode/templates/room/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Room{% endblock %}

{% block body %}
    <h1>Edit Room</h1>

    {{ include('room/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('room_index') }}">back to list</a>

    {{ include('room/_delete_form.html.twig') }}
{% endblock %}

discode/templates/room/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Room index{% endblock %}

{% block body %}
    <h1>Room index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for room in rooms %}
            <tr>
                <td>{{ room.id }}</td>
                <td>{{ room.nom }}</td>
                <td>
                    <a href="{{ path('room_show', {'id': room.id}) }}">show</a>
                    <a href="{{ path('room_edit', {'id': room.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('room_new') }}">Create new</a>
{% endblock %}

discode/templates/room/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Room{% endblock %}

{% block body %}
    <h1>Create new Room</h1>

    {{ include('room/_form.html.twig') }}

    <a href="{{ path('room_index') }}">back to list</a>
{% endblock %}

discode/templates/room/show.html.twig
{% extends 'base_lte.html.twig' %}

{% block title %}{{ room.nom }}{% endblock %}
{% block nomSalon %}{{ room.nom }}{% endblock %}

{% block chat %}

    <!-- DIRECT CHAT -->
    <div class=" direct-chat direct-chat-primary" >
        <!-- /.card-header -->
        <!-- Conversations are loaded here -->
        <div class="direct-chat-messages" style="height: 50em !important;">
            {% for message in messages %}
                {% if message.user.username == app.user.username %}
                    <!-- Message to the right -->
                    <div class="direct-chat-msg right">
                        <div class="direct-chat-infos clearfix">
                            <span class="direct-chat-name float-right">{{ message.user.username }}</span>
                            <span class="direct-chat-timestamp float-left">{{ message.dateCreation|date("m/d/Y") }}</span>
                        </div>
                        <!-- /.direct-chat-img -->
                        <div class="direct-chat-text">
                            {{ message.message }}
                        </div>
                        <!-- /.direct-chat-text -->
                    </div>
                    <!-- /.direct-chat-msg -->
                {% else %}
                    <!-- Message. Default to the left -->
                    <div class="direct-chat-msg">
                        <div class="direct-chat-infos clearfix">
                            <span class="direct-chat-name float-left">{{ message.user.username }} </span>
                            <span class="direct-chat-timestamp float-right">{{ message.dateCreation|date("m/d/Y") }} </span>
                        </div>
                        <!-- /.direct-chat-img -->
                        <div class="direct-chat-text">
                            {{ message.message }}
                        </div>
                        <!-- /.direct-chat-text -->
                    </div>
                    <!-- /.direct-chat-msg -->
                {% endif %}
            {% endfor %}
        </div>
        <!-- /.direct-chat-pane -->
        <div class="card-footer">
            <form action="{{ path('send', {room : room.id}) }}" method="post">
                <div class="input-group">
                    <input type="text" name="sendMessage" placeholder="Ecrire un message ..." class="form-control">
                    <span class="input-group-append">
                      <button type="submit" class="btn btn-primary">Envoyer</button>
                    </span>
                </div>
            </form>
        </div>
        <!-- /.card-footer-->
    </div>

    <a href="{{ path('room_index') }}">back to list</a>

    {{ include('room/_delete_form.html.twig') }}
{% endblock %}
{% block javascripts %}
    <script>

        const url = new URL('http://127.0.0.1:3000/hub');
        url.searchParams.append('topic', 'http://127.0.0.1:8000/room/'+{{ room.id }});
        const eventSource = new EventSource(url, {withCredentials:true});
        eventSource.onmessage = e => {
            const data = JSON.parse(e.data);
            if(data.message){
                document.querySelector(".direct-chat-messages").insertAdjacentHTML('afterbegin', '<div class="direct-chat-msg">'+
                    '<div class="direct-chat-infos clearfix">'+
                    '<span class="direct-chat-name float-left">'+data.user+'</span>'+
                    '<span class="direct-chat-timestamp float-right"></span>'+
                    '</div>'+
                    '<!-- /.direct-chat-img -->'+
                    '<div class="direct-chat-text">'+ data.message +
                    '</div>'+
                    '<!-- /.direct-chat-text -->'+
                    '</div>');
            }
        };

    </script>
{% endblock %}